version: "3.7"
services:

  fastapi:
    env_file:
    - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000

  postgres:
    env_file:
    - .env
    image: postgres:latest
    ports:
    - 5432:5432